# Week 1 Lab Assignments

You are required to implement the following functions:
- `homogenous_transform_2D` - Perform homogenous transformations for a 2D system
- `homogenous_transform_3D` - Perform homogenous transformations for a 3D system
- `chain_transforms` - Perform a chain of 3D transformations in the given order


In [1]:
# import required libraries
import numpy as np
import matplotlib.pyplot as plt
# To render plots inline
%matplotlib inline

# For unit tests
from tester import LabTester
lab_tester = LabTester()

ModuleNotFoundError: No module named 'numpy'

In [2]:
# Homogenous 2D Transformation
def homogenous_transform_2D(V:np.ndarray, U:np.ndarray, theta:float) -> np.ndarray:
    """
    Input:
        V       - initial vector
        U       - translation vector
        theta   - angle in degrees
    Output: resulting coordinates after rotating V by theta and translating by U
    """

    # Your code here

    # Convert angle to radians
    theta_rad = np.radians(theta)
    
    # Rotation matrix for 2D
    R = np.array([
        [np.cos(theta_rad), -np.sin(theta_rad)],
        [np.sin(theta_rad), np.cos(theta_rad)]
    ])
    
    # Apply rotation and translation
    rotated_point = R @ V
    transformed_point = rotated_point + U
    return transformed_point
    pass

## Lab 1: Homogeneous Transformation in 2D
- *Theory*: Translating and rotating a point using homogeneous transformations.
- *Task*: Implement a function that applies a 2D homogeneous transformation matrix to a given point.
- *Expected Output*: Given a vector $(1,0)$ applying a translation of $(3,4)$ and a $\theta = 45°$ rotation, the transformed point should be $(3.707, 4.707)$

In [3]:
lab_tester.test_homogeneous_transform_2d(homogenous_transform_2D)


=== Testing 2D Homogeneous Transformation Implementation ===
✅ Combined transform: translation(3,4) + rotation(45°)
✅ Pure translation: no rotation


In [ ]:
# Homogenous 3D Transformation
def homogenous_transform_3D(V:np.ndarray, U:np.ndarray, theta:dict) -> np.ndarray:
    """
    Input:
        V       - initial vector
        U       - translation vector
        theta   - dictionary of angles with the 'x', 'y' and 'z' angles
    Output: resulting coordinates after rotating V by theta and translating by U
    """

    # Your code here

    # Convert angles to radians
    theta_x = np.radians(theta.get('x', 0))
    theta_y = np.radians(theta.get('y', 0))
    theta_z = np.radians(theta.get('z', 0))

    # Rotation matrix for 3D around x, y, and z axes
    R_x = np.array([
        [1, 0, 0],
        [0, np.cos(theta_x), -np.sin(theta_x)],
        [0, np.sin(theta_x), np.cos(theta_x)]
    ])
    
    R_y = np.array([
        [np.cos(theta_y), 0, np.sin(theta_y)],
        [0, 1, 0],
        [-np.sin(theta_y), 0, np.cos(theta_y)]
    ])
    
    R_z = np.array([
        [np.cos(theta_z), -np.sin(theta_z), 0],
        [np.sin(theta_z), np.cos(theta_z), 0],
        [0, 0, 1]
    ])
    
    # Combine the rotations in the order of X, Y, and Z
    R = R_x @ R_y @ R_z 
    
    # Apply rotation and translation
    rotated_point = R @ V 
    transformed_point = rotated_point.flatten() + U  # Ensure correct addition
    print(transformed_point)
    
    
    return transformed_point

    pass

## Lab 4: Homogeneous Transformation in 3D
- *Theory*: Extending 2D transformations to 3D space.
- *Task*: Implement a function that applies a 3D transformation matrix to a point in 3D.
- *Expected Output*: Given a vector $(2,3,4)$ appying a translation of $(5,5,5)$ and a rotation of $\theta = 90°$ about the z-axis the transformed point should be $(2,7,9)$.

In [25]:
lab_tester.test_homogeneous_transform_3d(homogenous_transform_3D)


=== Testing 3D Homogeneous Transformation Implementation ===
[2. 7. 9.]
❌ Combined 3D transform: translation(5,5,5) + rotation(90° about z)
   Expected: [-8, 7, 9]
   Got: [2. 7. 9.]
[5. 7. 9.]
✅ Pure 3D translation: no rotation
[1.000000e+00 6.123234e-17 1.000000e+00]
✅ Pure rotation about x-axis
[3.74939946e-33 1.22464680e-16 1.00000000e+00]
✅ Combined rotations about x, y, and z axes
[ 2.00000000e+00 -3.00000000e+00  2.22044605e-16]
❌ Rotations with Negative Translation
   Expected: [2, -1, 0]
   Got: [ 2.00000000e+00 -3.00000000e+00  2.22044605e-16]
[-2.  6.  1.]
❌ Rotations by odd angles with Translation
   Expected: [2, -4, 7]
   Got: [-2.  6.  1.]


## Lab 5: Chain Transformations
- *Theory*: Combining multiple transformations using matrix multiplication.
- *Task*: Implement a function that applies multiple homogeneous transformations sequentially.
- *Expected Output*: Given a sequence of rotations and translations, compute the final transformed position.

In [6]:
# Chain transformations
def chain_transforms(V:np.ndarray, transforms:list) -> np.ndarray:
    """
    Input:
        V           - initial vector
        transforms  - list of 'translation' and 'rotation' - ex:{'translation': np.array([0, 0, 0]), 'rotation': {'z': 0}}
    Output: resulting coordinates after appyling the transforms in the given order
    """

    # Your code here

    for transform in transforms:
        # Make sure to correctly apply translation and rotation using the 3D transform function
        translation_v = transform.get('translation', np.array([0, 0, 0]))
        rotation_v = transform.get('rotation', {'x': 0, 'y': 0, 'z': 0})
        
        # Apply the homogeneous transformation
        V = homogenous_transform_3D(V, translation_v, rotation_v)
    return V

    pass

In [7]:
lab_tester.test_chain_transformations(chain_transforms)


=== Testing Chain Transformations Implementation ===
✅ Chain of two translations
✅ Translation followed by rotation
❌ Complex chain of transformations
   Expected: [1, 3, -2]
   Got: [ 1.11022302e-16  1.00000000e+00 -1.00000000e+00]
✅ Chain of identity transformations
❌ Complex transformations
   Expected: [3.607, -2.068, 1.234]
   Got: [ 1.8308927  -0.38874408 -2.0454028 ]


In [8]:
# Summary of test results
lab_tester.print_summary()


=== Test Summary ===
Passed: 8/13 tests
❌ 5 tests failed
